[tools]
node = "25.8.1"
go = "1.26.1"
pnpm = "10.32.1"
buf = "1.66.1"
"aqua:sqlc-dev/sqlc" = "1.30.0"
"aqua:pressly/goose" = "3.27.0"
just = "1.47.0"
lefthook = "2.1.4"
"npm:oxlint" = "1.56.0"
"npm:oxfmt" = "0.41.0"
"aqua:golangci/golangci-lint" = "2.11.3"
"aqua:gitleaks/gitleaks" = "8.30.0"
"aqua:air-verse/air" = "1.64.5"
"aqua:a-h/templ" = "0.3.1001"
